-- Create the links table
CREATE TABLE links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    category TEXT DEFAULT 'Uncategorized'
);

-- Enable Row Level Security (RLS)
ALTER TABLE links ENABLE ROW LEVEL SECURITY;

-- Create policy for public access (Simple mode)
-- WARNING: In a production app, you should add user authentication
CREATE POLICY "Allow public read and write" ON links
    FOR ALL
    USING (true)
    WITH CHECK (true);
